### ISSUE TITLE
技術選定

### ISSUE THREAD

**Issue by yu23ki14** [codeforjapan/OpenDataTools#1]
- 開発言語（個人的にはTypescriptがいいです）

- フロントエンドフレームワーク（React?Vue?）
  - ページ少なく複雑なセッション管理とか必要ないと思うのでNext Nuxtは使うまでもないかなとおもいます。
  - 編集可能なテーブルフレームワーク（AG-Grid?）

- バリデータ、フォーマッタのnpmとして切り出す部分
  - npmパッケージ公開が簡単にできるようなフレームワークありそう。

**Comment by kaizumaki** [comment]
# メモ

## 開発言語
- 私もTypeScriptでよいと思います。

## フロントエンドフレームワーク
- SPAでいけるはずなので、ReactかVueでいいと思います。
- プロトタイプといえど将来を見据えると現時点でVue2の選択肢は切っていいと思います。
- ReactかVue3か、というところで、Vue3は現状こなれてないかと思いますので、Reactでいくのが無難かなあと思います。

## 使用ライブラリ
- テーブルフレームワーク「AG-Grid」って初めて知りました。
- UIをささっと実装するなら[mui](https://mui.com/) がよいかと思います。
  - muiにもTableコンポーネントがあります。表形式のデータをどこまでフレキシブルに操作できるようにするかによって、AG-Gridと比較検討したいと思います。
  - UIをスクラッチで作成する場合はmuiは不要です（むしろ導入しない方がいい）。
- テストは実装したほうがいいと思います。テストフレームワークに明るくないのですが、やはりjestでしょうか？

## npmパッケージ化
- [公式ドキュメント](https://docs.npmjs.com/packages-and-modules/contributing-packages-to-the-registry)
- 特にフレームワーク的なものはなさそう（？）
- 泥臭く手作業するほうが早いかもです。
