### ISSUE TITLE
【webclient】セル単位編集画面の緯度経度インターフェース

### ISSUE THREAD

**Issue by yu23ki14** [codeforjapan/OpenDataTools#100]
セル単位編集画面の緯度経度インターフェースのベースを実装。細かなデザインは後ほど当てていくので、一旦機能面だけで問題ない。
<img width="1512" alt="Group 1 (1)" src="https://user-images.githubusercontent.com/18475563/195004996-75efe748-298d-4be9-8f2b-117b018a4603.png">

**仕様メモ**
- マップ上でピンを移動させたら、その緯度経度にデータを書き換える。小数点6桁まで。

**Comment by kur00** [comment]
やってますー
