### ISSUE TITLE
【webclient】複数のCSVファイルがドロップされたときの挙動

### ISSUE THREAD

**Issue by yu23ki14** [codeforjapan/OpenDataTools#103]
現状
複数のファイルがドロップされたとき、見かけ上末尾のものがセットされるようになっている。

あるべき姿
複数ファイルには一旦非対応として、lengthでファイル数を取って明示的に一つづつファイルを選択してくださいとアラートを出す。

**Comment by Murayu0225** [comment]
このissueやります
