### ISSUE TITLE
【webclient】CSVファイルを直接選択したときの挙動

### ISSUE THREAD

**Issue by yu23ki14** [codeforjapan/OpenDataTools#104]
現状
ドロップではなく直接選択した時、ファイルが選択されずに無限ループする

あるべき姿
ドロップした時同様、ファイルが選択されているようにする。

環境
windows & brave

**Comment by Syuparn** [comment]
こちらのissue着手したいと思います！

**Comment by Syuparn** [comment]
:memo:

Windows & Chromeの場合は、直接選択した際

- ファイルは選択される
- 選択画面が再度表示される
- 再度選択すると選択画面は消える
