### ISSUE TITLE
[データ形式チェック]電話番号の形式が正しいか？

### ISSUE THREAD

**Issue by champierre** [codeforjapan/OpenDataTools#11]

**Comment by kaizumaki** [comment]
これやってみます！

**Comment by kaizumaki** [comment]
行政基本情報データ連携モデル
電話番号
https://cio.go.jp/sites/default/files/uploads/documents/1015-5_gyousei_data_model_phone.pdf

**Comment by kaizumaki** [comment]
## ルール
### 国内番号の場合
- 半角数字、半角ハイフン `-` 、半角カッコ `(` `)` のみ使用可能
- スペースは使用しない
- 半角数字は10桁（固定電話）か11桁（携帯電話）
- 半角数字は0から始まる

### 国際番号の場合
- `+` から始まる
- `+` の直後に0がくることはない
- `+` の後に国番号（半角数字）がきて、その後は半角スペースを入れる
- `+` +国番号+半角スペースの直後に0がくることはない
- `+` +国番号+半角スペースの後は半角数字、半角ハイフン `-` 、半角カッコ `(` `)` のみ使用可能
- 半角数字は15桁以内

**Comment by kaizumaki** [comment]
## 実装アイディア
- 以下の３パターン以外は電話番号とみなさない
  - `^0`
例：099999-9999、0120-999999
  - `^\(0\d+\)`
例：(09)9999-9999、(099)999-9999、(09999)9-9999
  - `^\+[1-9]+\s\([1-9]+\)`
例：+81 (9)9999-9999
- 上記３パターンの後ろは半角数字と半角ハイフン `-` しか許可しない
- 半角数字だけ抜き取って10桁以上15桁以内とならないものは許可しない
