### ISSUE TITLE
【webclient】ローカルストレージ関連

### ISSUE THREAD

**Issue by yu23ki14** [codeforjapan/OpenDataTools#117]

**Comment by kaizumaki** [comment]
削除ボタンが欲しいです！

**Comment by kaizumaki** [comment]
ステップ４の完了時に削除するのは最低限必要かも。

**Comment by yu23ki14** [comment]
@kaizumaki 
これ、完了時に削除しちゃうよりも、トップの一覧で削除できるようにしたほうがいいと思うんですがどうですか？
たとえば、一旦完成して上長確認挟むみたいなワークフローあるとおもうので

**Comment by kaizumaki** [comment]
@yu23ki14 たしかに、その用途はありそうですね 👀 ステップ４でcsvをダウンロードさせる手間と、local storageに（気づかない間に？）溜まっていくことのトレードオフかもしれないです。

ちょっと思いついちゃったんですが、逆にステップ４の「完了」時に必ずcsvをダウンロードさせるUIは必要だなと。
csvをダウンロードすれば、再度ステップ１のアップロードから始められますしね。
