### ISSUE TITLE
【webclient】セルデータ編集ページで名称を表示する。

### ISSUE THREAD

**Issue by yu23ki14** [codeforjapan/OpenDataTools#121]
![image](https://user-images.githubusercontent.com/18475563/196645895-00dcee26-5bd0-4de9-b0f1-d05b2d38d024.png)

「名称がここにくる」のところに名称をいれる

**Comment by Syuparn** [comment]
各行の「名称」列を「名称がここに来る」の部分に表示されるようにする

**Comment by kaizumaki** [comment]
行番号も併記する。
