### ISSUE TITLE
ステップ４完了時にcsvダウンロードとlocal storage削除を行う

### ISSUE THREAD

**Issue by kaizumaki** [codeforjapan/OpenDataTools#133]
- 作業完了時にcsvダウンロードとlocal storage削除を行うようにする
- ステップ４にある「ダウンロード」ボタンは削除する
- csvダウンロード後にマップ表示が可能となる

figmaあり

![step4-3](https://user-images.githubusercontent.com/14883063/197377690-66cfd2b8-692e-402e-8275-6df175f8f98c.png)

![step4-5](https://user-images.githubusercontent.com/14883063/197377703-cb7d8990-b2e3-4ca3-9e54-b8bba720eab4.png)

**Comment by kaizumaki** [comment]
chakra uiのmodalコンポーネント
https://chakra-ui.com/docs/components/modal/usage

**Comment by Syuparn** [comment]
こちら（ローカルストレージ削除関数ができたら）着手したいと思います！
