### ISSUE TITLE
トップ画面のスタイルを整える

### ISSUE THREAD

**Issue by kaizumaki** [codeforjapan/OpenDataTools#145]
トップ画面~~とmap画面~~のスタイルを整えます。
追記：issueを分けます。

現在↓

![ホーム-Bulletproof-React](https://user-images.githubusercontent.com/14883063/198412309-6101fd2d-4329-4492-ba10-ec3e646c5ce4.png)

**Comment by Syuparn** [comment]
こちら着手したいと思います！

**Comment by Syuparn** [comment]
layoutのコンポーネントも新たに作成する必要があるかも

- `webclient/src/components/Layout/ContentLayout.tsx` の `Box` を削除して、ヘッダーを消す
- 別途背景の指定は必要かも
