### ISSUE TITLE
データが大きいファイルをアップロードするとローカルストレージに保存できない

### ISSUE THREAD

**Issue by kur00** [codeforjapan/OpenDataTools#146]
related : #131 

localstorageのデータ上限に引っかかり下記エラーが出てしまう。
```
DOMException: Failed to execute 'setItem' on 'Storage': Setting the value of 'xxx' exceeded the quota.
```

[参照](https://web.dev/i18n/ja/storage-for-the-web/)
```
LocalStorageは同期して働き、
メインスレッドをブロックするため、使用を避けるべきでしょう。データ量は、約5MBに制限されており、
文字列しか含めることができません。ウェブワーカーやサービスワーカーからはアクセスできません。
```

自治体によっては規模の大きいデータをフォーマットとする必要があるので、対応策から考えていきたい。

**Comment by kota-yata** [comment]
LocalStorageでは限界がありそうなので、[IndexedDB](https://developer.mozilla.org/ja/docs/Web/API/IndexedDB_API/Basic_Terminology)の使用を検討した方が良いかもしれません。IndexedDBはブラウザ上のKVSみたいな感じで、文字列しか保存できないLocalStorageに比べてBlobなど他の形式での保存にも対応しているというメリットがあります。

また、kur00さんが参照している記事にある通り、Chromeはディスクの80%、Firefoxは50%、Safariは1GBをブラウザ上ストレージのために使用することができ、Cache APIやService Workerなどを使用していない場合そのほぼ全てをIndexedDBのために使うことができます。さすがにディスクの80%をこのアプリだけで占有するのはエグいので[Storage API](https://developer.mozilla.org/ja/docs/Web/API/Storage_API)などでの制限は必要かもしれませんが、少なくともこれで現状のエラーは解決できるかと思います。

**Comment by kaizumaki** [comment]
@kota-yata コメントありがとうございます！
たしかにIndexedDBへの乗り換えはアリのような気がしてきました。
いずれにせよ制限をかけておくのは必須でしょうね。
