### ISSUE TITLE
Read.meの整備

### ISSUE THREAD

**Issue by yu23ki14** [codeforjapan/OpenDataTools#173]

**Comment by kaizumaki** [comment]
#189 も一緒に対応をお願いしたいです。

**Comment by forestgtree** [comment]
@kaizumaki 
項目名とバリデーションの処理内容について
以下の内容で追記をお願いします🙏

項目名 | バリデーション（確認処理内容）
-- | --
都道府県コード又は市区町村コード | 6桁数値であるか
NO | 10桁数値であるか
都道府県名 | 県や都まで含めた、正式名称であるか
市区町村名 | 市区町村まで含めた、正式名称であるか
名称 | 確認処理無し
名称_カナ | カタカナであるか（半角入力自動処理）
名称_通称 | 確認処理無し
POIコード | ４桁数値又は、実在するPOI数値であるか（独自にPOI一覧を用意している）
住所 | Geoloniaの住所データ（オープンソース）を利用し正規化
方書 | 確認処理無し
緯度 | 10進数、小数点以下6桁であるか、日本領域であるか
経度 | 10進数、小数点以下6桁であるか、日本領域であるか
電話番号 | 10桁以上15桁以内であるか   国際電話及び市外局番始まりであるか（独自に市外局番一覧を用意している）   セパレーター（半角ハイフン「-」）が含まれるか
内線番号 | 確認処理無し
法人番号 | 確認処理無し
団体名 | 確認処理無し
利用可能曜日 | 曜日漢字（月火水木金土日）であるか
開始時間 | 時間表記がhh:mmであるか
終了時間 | 時間表記がhh:mmであるか
利用可能日時特記事項 | 確認処理無し
説明 | 確認処理無し
バリアフリー情報 | 確認処理無し
URL | 「https://」書き出しと、それに続く表記であるか
備考 | 確認処理無し

**Comment by forestgtree** [comment]
推奨（非推奨）のブラウザ環境についても、追記をお願いします🙏

- 推奨
     - Microsoft Edge 最新版
     - Chrome 最新版
- 非推奨
     - Internet Explorer
     - macOS Safari
