### ISSUE TITLE
各ステップごとに、作業内容の説明文を追記する。（トップページに含まれている内容）

### ISSUE THREAD

**Issue by yu23ki14** [codeforjapan/OpenDataTools#174]

**Comment by forestgtree** [comment]
Figmaデザインにへの反映着手します。

**Comment by forestgtree** [comment]
各ステップ画面ごとに、見出し（h1）の下に説明文を追記しました。

### 文言修正内容

## ステップ１
**初期画面**
`検証を行いたいファイルを下記の枠内にドラック&ドロップしてください`

**背景黄色のエラーメッセージ**
`Excel（.xls/.xlsx）のファイルはアップロード対応していませんので、Excelファイルの場合はファイル形式を「CSV UTF-8(コンマ区切り)(.csv)」で保存した状態で、アップロードしてください。`

**アップロード完了後**
`次のステップに進むと、検証前に必要な自動変換がはじまります`

## ステップ２
**初期画面**
`アップロードしたファイル内容を確認し検証前に必要な変換を行っています`

**変換後**
`次のステップにすすむと、政府が公開している「推奨データセット」のデータ項目名と整合を行っていただきます`

## ステップ３
`変換が完了したCSVファイルと、政府が公開している「推奨データセット」のデータ項目名と整合を行います`

## ステップ４
`項目名別に細かく修正ポイントが表示されますので、メッセージに従ってデータ形式を修正してください`
