### ISSUE TITLE
バリデーションチェック未解決でも完了ボタンが押せてしまう

### ISSUE THREAD

**Issue by Murayu0225** [codeforjapan/OpenDataTools#179]

**Comment by Syuparn** [comment]
こちら着手したいと思います！

**Comment by Syuparn** [comment]
原因は2つあるとみられます。

1. エラー判定が読み込みのタイムラグで「エラーなし」と判定されてしまう
2. エラー判定でもボタンが押せてしまう


2については、STEP4の「完了ボタン」の `onClick` が `as` で指定したオブジェクトのものとして解釈され `isDisabled` でブロックできていないのが原因と考えられます。
https://github.com/chakra-ui/chakra-ui/issues/1436
