### ISSUE TITLE
最終のマップ表示画面よりトップページへの遷移ボタンが不足している。

### ISSUE THREAD

**Issue by yu23ki14** [codeforjapan/OpenDataTools#186]

**Comment by forestgtree** [comment]
こちらのデザイン作業に着手します。
#178 操作説明も入るため、関連するデザイン改修になります。

**Comment by forestgtree** [comment]
マップ画面のナビゲーション追加（上部エリア）と、操作説明（マップの下部エリア）について反映しました。
![map](https://user-images.githubusercontent.com/55567929/206836366-466c2a2c-2366-4d51-846f-c2e9adeaa93c.png)

**Comment by Murayu0225** [comment]
こちらも対応します
