### ISSUE TITLE
項目別に修正を行うこと（左メニューの存在）に気づきにくい。

### ISSUE THREAD

**Issue by yu23ki14** [codeforjapan/OpenDataTools#188]

**Comment by forestgtree** [comment]
こちらの改修案ですが
現状、ページの上部（ファイル名の下）に表示されているアラート内容を
少し表現をシンプルにして、各項目メニューにラベルを表示するデザイン修正を行いたいと思います😊
イメージとしては、メールの受信ボックスのように未読件数が表示されるような感じかと思っています。

**Comment by forestgtree** [comment]
@yu23ki14 

現状、ページ上部に表示されている修正件数を、左の項目メニュー内に含める形にデザインを修正したいと思います。

メニューごとの情報区切りが必要なため罫線を追加。
各メニューの先頭に入れていたアイコンを削除。

before
<img width="285" alt="スクリーンショット 2022-12-10 15 32 21" src="https://user-images.githubusercontent.com/55567929/206835761-a1883113-9eb2-47e7-b517-4ff0d91d1540.png">

after
<img width="376" alt="スクリーンショット 2022-12-10 15 28 34" src="https://user-images.githubusercontent.com/55567929/206835639-10a276b1-3f97-4c35-85ad-6bcf54a27733.png">
