### ISSUE TITLE
[データ形式チェック]バリアフリー情報の形式が正しいか？（; で区切る）

### ISSUE THREAD

**Issue by champierre** [codeforjapan/OpenDataTools#21]

**Comment by ocean3fish** [comment]
バリアフリー情報のcontrolled vocabularies
（出典：[デジタル庁 > 推奨データセット > データ項目定義書](https://www.digital.go.jp/resources/data_dataset/)）

```
優先駐車場有り
多目的トイレ有り
車椅子貸出有り
車椅子対応公衆電話有り
盲導犬・介助犬・聴導犬同伴可
スロープ有り
段差無し
エレベーター有り
エスカレーター有り
階段無し
手すり有り
点字ブロック有り
```

**Comment by champierre** [comment]
これ、やりますね。

**Comment by champierre** [comment]
https://github.com/codeforjapan/OpenDataTools/issues/21#issuecomment-1193086841 で挙げられた項目を ; で区切るというルールがあるが、自由入力の項目も認められているため、データの内容をバリデートするのは難しい。
