### ISSUE TITLE
CSVインポート画面のスタイリング

### ISSUE THREAD

**Issue by yu23ki14** [codeforjapan/OpenDataTools#79]
**ファイルアップロード前**
https://www.figma.com/file/TSMMVFAsUwkosBmY7S1FSd/opendata_support_tool-UI?node-id=174%3A7842

**ファイルアップロード後**
https://www.figma.com/file/TSMMVFAsUwkosBmY7S1FSd/opendata_support_tool-UI?node-id=531%3A8140

**Comment by kaizumaki** [comment]
ステップのUIは他ページとまとめて別issueで対応しようと思うので、こちらのissueでは一旦無視してください 🙏 
![スクリーンショット 2022-10-05 18 52 19](https://user-images.githubusercontent.com/14883063/194033221-642eac7a-71fe-4289-bb3d-09e5e1e2ec2f.png)

**Comment by kaizumaki** [comment]
こちらやりますね。

**Comment by kaizumaki** [comment]
@Murayu0225 さんがやってくれていたので引き継ぎます。
