### ISSUE TITLE
自動変換ページのスタイリング

### ISSUE THREAD

**Issue by yu23ki14** [codeforjapan/OpenDataTools#80]
**変換中**
https://www.figma.com/file/TSMMVFAsUwkosBmY7S1FSd/opendata_support_tool-UI?node-id=473%3A7591

**変換後**
https://www.figma.com/file/TSMMVFAsUwkosBmY7S1FSd/opendata_support_tool-UI?node-id=514%3A8584

**Comment by kaizumaki** [comment]
ステップのUIは他ページとまとめて別issueで対応しようと思うので、こちらのissueでは一旦無視してください 🙏 

![スクリーンショット 2022-10-05 18 52 19](https://user-images.githubusercontent.com/14883063/194033221-642eac7a-71fe-4289-bb3d-09e5e1e2ec2f.png)

**Comment by kaizumaki** [comment]
こちらやりますね。
