### ISSUE TITLE
セル単位データ編集画面のスタイリング

### ISSUE THREAD

**Issue by yu23ki14** [codeforjapan/OpenDataTools#82]
**編集中**
https://www.figma.com/file/TSMMVFAsUwkosBmY7S1FSd/opendata_support_tool-UI?node-id=475%3A7687

**完了**
https://www.figma.com/file/TSMMVFAsUwkosBmY7S1FSd/opendata_support_tool-UI?node-id=537%3A10538

**Comment by kaizumaki** [comment]
ステップのUIは他ページとまとめて別issueで対応しようと思うので、こちらのissueでは一旦無視してください 🙏 

![スクリーンショット 2022-10-05 18 52 19](https://user-images.githubusercontent.com/14883063/194033221-642eac7a-71fe-4289-bb3d-09e5e1e2ec2f.png)

**Comment by kaizumaki** [comment]
こちらやりますね。
